package claudebridge

import (
	"context"
	"strings"

	"github.com/justphantom/lark-bridge/internal/bridgebase"
	"github.com/justphantom/lark-bridge/internal/cmdutil"
)

// cmdModel pins, clears, or interactively selects the model for the current
// chat. Forms:
//   - /model            → pop a selection card (options from config; with a
//     custom-input box for a model not listed)
//   - /model clear      → clear the pin (fall back to Claude's default)
//   - /model <spec>     → pin <spec> directly (e.g. /model claude-sonnet-4-5)
//
// The spec is passed verbatim to the CLI as --model on the next run.
func (h *Handler) cmdModel(ctx context.Context, chatID string, args []string) (commandResult, error) {
	b, err := h.ensureBinding(chatID, "", "", "", "")
	if err != nil {
		return commandResult{Body: err.Error()}, err
	}

	if len(args) == 0 {
		return h.runModelPicker(chatID, b.ModelSpec, bridgebase.ReplyToID(ctx)), nil
	}
	if args[0] == "clear" {
		return clearModelSpec(h, chatID, b.ModelSpec), nil
	}

	spec := strings.Join(args, " ")
	old := b.ModelSpec
	if old == "" {
		old = "默认"
	}
	h.Router.SetModelSpec(chatID, spec)
	cmdutil.LogSettingChange(h.Logger, chatID, "model", spec)
	return cmdutil.ChangeResult("模型", old, spec, "下次提问生效。"), nil
}

// runModelPicker drives the interactive model selection. It emits the Question
// card via askAndWait (which blocks in this dispatcher goroutine for the
// user's answer), pins the result, and emits a confirmation Notice. Returns
// Handled so the dispatcher skips its default Notice (the confirmation is
// already emitted by emitNotice, and the dispatcher's ctx may have expired).
// replyToID carries the triggering message's ID so the Question card morphs
// the command's progress card in place (one card end-to-end); a failure
// terminates that same card via emitPromptNotice.
func (h *Handler) runModelPicker(chatID, oldSpec, replyToID string) commandResult {
	choice, messageID, err := h.AskAndWait(chatID, replyToID, "模型", "选择模型", bridgebase.StaticOptions(h.modelOptions), true)
	if err != nil {
		h.EmitPromptNotice(chatID, replyToID, "error", "选择失败", err.Error())
		return commandResult{Body: err.Error(), Handled: true}
	}
	old := oldSpec
	if old == "" {
		old = "默认"
	}
	h.Router.SetModelSpec(chatID, choice)
	cmdutil.LogSettingChange(h.Logger, chatID, "model", choice)
	res := cmdutil.ChangeResult("模型", old, choice, "下次提问生效。")
	h.EmitCardUpdateLogged(chatID, messageID, "success", "已切换模型", res.Body, res.Field, res.Before, res.After)
	return commandResult{Handled: true}
}

// clearModelSpec is the /model clear path.
func clearModelSpec(h *Handler, chatID, oldSpec string) commandResult {
	old := oldSpec
	if old == "" {
		old = "默认"
	}
	h.Router.SetModelSpec(chatID, "")
	cmdutil.LogSettingChange(h.Logger, chatID, "model", "")
	return cmdutil.ChangeResult("模型", old, "默认", "已清除模型设置，将使用 Claude 默认模型。")
}

// settableEffortLevels is the set of valid --effort values the /effort
// command accepts. These map directly to Claude Code CLI effort levels.
var settableEffortLevels = map[string]struct{}{
	"low":    {},
	"medium": {},
	"high":   {},
	"xhigh":  {},
	"max":    {},
}

func isSettableEffortLevel(level string) bool {
	_, ok := settableEffortLevels[level]
	return ok
}

// cmdEffort is generated by bridgebase.MakeEnumPicker (see commands.go init).
// The picker shape — pin / clear / interactively select from a static list
// with allowCustom=false — is byte-identical to omp's /thinking, so the
// shared factory centralises the ~70 lines both backends used to spell
// inline. Setter wires the EffortLevel router field + the structured-log
// line.
func (h *Handler) cmdEffort(ctx context.Context, chatID string, args []string) (commandResult, error) {
	return bridgebase.MakeEnumPicker(h.Core, bridgebase.EnumPickerConfig{
		Spec:       cmdutil.Spec{Name: "/effort", Summary: "设置推理级别；不带参数弹出选择；传 clear 清除", Args: "[level|clear]", Title: "已设置推理级别", Level: "success"},
		FieldLabel: "推理级别",
		LogKey:     "effort_level",
		Options:    h.effortOptions,
		Default:    "默认",
		ErrorHint:  "可选 low | medium | high | xhigh | max",
		Valid:      isSettableEffortLevel,
	}, bridgebase.EnumPickerAccessors[*Handler]{
		Ensure: func(h *Handler, chatID string) error {
			_, err := h.ensureBinding(chatID, "", "", "", "")
			return err
		},
		Get: func(h *Handler, chatID string) string {
			b, _ := h.Router.Lookup(chatID)
			return b.EffortLevel
		},
		Set: func(h *Handler, chatID, v string) {
			h.Router.SetEffortLevel(chatID, v)
			cmdutil.LogSettingChange(h.Logger, chatID, "effort_level", v)
		},
	}).Handler(h, ctx, chatID, args)
}

// cmdHelp returns the auto-generated command list.
func (*Handler) cmdHelp(_ context.Context, _ string, _ []string) (commandResult, error) {
	return commandResult{Body: renderCmdHelp()}, nil
}
